[params]
DB_CONF_FILE                          =/usr/local/src/area_matching/config/db_conf_v6.ini
WORKING_SCHEMA                        =
AREA_TABLE_INIT                       =drainage_basin_w_fr_lu_20251016
COUNTRY_CODE_W                        =
LANDMASK_TABLE                        =au.administrative_unit_area_1
LAND_COVER_TYPE_NAME                  =land_cover_type 
TYPE_LAND_AREA                        =land_area
TYPE_INLAND_WATER                     =inland_water
NATIONAL_IDENTIFIER_NAME              =w_national_identifier
W_TAG_NAME                            =w_tag

#Small Area Merger
MA_SMALL_AREA_THRESHOLD               =30000
MA_SLIM_AREA_THRESHOLD                =50

[at#ch]
COUNTRY_CODE_W                        =at#ch

[at#cz]
COUNTRY_CODE_W                        =at#cz

[at#li]
COUNTRY_CODE_W                        =at#li

[be#fr]
COUNTRY_CODE_W                        =be#fr

[be#lu]
COUNTRY_CODE_W                        =be#lu

[be#nl]
COUNTRY_CODE_W                        =be#nl

[ch#fr]
COUNTRY_CODE_W                        =ch#fr

[es#fr]
COUNTRY_CODE_W                        =es#fr

[fr#lu]
COUNTRY_CODE_W                        =fr#lu